// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: serviceb.proto

package servicebv1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FlipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	A   int32  `protobuf:"varint,2,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *FlipRequest) Reset() {
	*x = FlipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlipRequest) ProtoMessage() {}

func (x *FlipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlipRequest.ProtoReflect.Descriptor instead.
func (*FlipRequest) Descriptor() ([]byte, []int) {
	return file_serviceb_proto_rawDescGZIP(), []int{0}
}

func (x *FlipRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FlipRequest) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

type FlipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg   string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Rcode int32  `protobuf:"varint,2,opt,name=rcode,proto3" json:"rcode,omitempty"`
}

func (x *FlipResponse) Reset() {
	*x = FlipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlipResponse) ProtoMessage() {}

func (x *FlipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlipResponse.ProtoReflect.Descriptor instead.
func (*FlipResponse) Descriptor() ([]byte, []int) {
	return file_serviceb_proto_rawDescGZIP(), []int{1}
}

func (x *FlipResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FlipResponse) GetRcode() int32 {
	if x != nil {
		return x.Rcode
	}
	return 0
}

var File_serviceb_proto protoreflect.FileDescriptor

var file_serviceb_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x16, 0x70, 0x61, 0x72, 0x74, 0x68, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x22, 0x2d, 0x0a, 0x0b, 0x46, 0x6c, 0x69, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x61, 0x22, 0x36, 0x0a, 0x0c, 0x46, 0x6c, 0x69, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x32,
	0x5c, 0x0a, 0x05, 0x45, 0x63, 0x68, 0x6f, 0x42, 0x12, 0x53, 0x0a, 0x04, 0x46, 0x6c, 0x69, 0x70,
	0x12, 0x23, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x68, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x69, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x68, 0x70, 0x6f, 0x77,
	0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x6c, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serviceb_proto_rawDescOnce sync.Once
	file_serviceb_proto_rawDescData = file_serviceb_proto_rawDesc
)

func file_serviceb_proto_rawDescGZIP() []byte {
	file_serviceb_proto_rawDescOnce.Do(func() {
		file_serviceb_proto_rawDescData = protoimpl.X.CompressGZIP(file_serviceb_proto_rawDescData)
	})
	return file_serviceb_proto_rawDescData
}

var file_serviceb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_serviceb_proto_goTypes = []interface{}{
	(*FlipRequest)(nil),  // 0: parthpower.serviceb.v1.FlipRequest
	(*FlipResponse)(nil), // 1: parthpower.serviceb.v1.FlipResponse
}
var file_serviceb_proto_depIdxs = []int32{
	0, // 0: parthpower.serviceb.v1.EchoB.Flip:input_type -> parthpower.serviceb.v1.FlipRequest
	1, // 1: parthpower.serviceb.v1.EchoB.Flip:output_type -> parthpower.serviceb.v1.FlipResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_serviceb_proto_init() }
func file_serviceb_proto_init() {
	if File_serviceb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serviceb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serviceb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serviceb_proto_goTypes,
		DependencyIndexes: file_serviceb_proto_depIdxs,
		MessageInfos:      file_serviceb_proto_msgTypes,
	}.Build()
	File_serviceb_proto = out.File
	file_serviceb_proto_rawDesc = nil
	file_serviceb_proto_goTypes = nil
	file_serviceb_proto_depIdxs = nil
}
